/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from "./Ownable";
export type { Election } from "./Election";

export { Ownable__factory } from "./factories/Ownable__factory";
export { Election__factory } from "./factories/Election__factory";
